name: MLflow CI Training

on:
  push:
    paths:
      - "Workflow-CI/MLProject/**"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: Workflow-CI/MLProject/conda.yaml
          activate-environment: smsml_env
          auto-activate-base: false

      - name: Run MLflow Project Training
        shell: bash -l {0}
        run: |
          conda activate smsml_env
          cd Workflow-CI/MLProject
          mlflow run . --entry-point main

      - name: Find latest run ID
        id: get_run
        shell: bash -l {0}
        run: |
          conda activate smsml_env
          ls Workflow-CI/MLProject/mlruns/0
          RUN_ID=$(ls -t Workflow-CI/MLProject/mlruns/0 | head -n 1)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model
          path: Workflow-CI/MLProject/mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/model

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image from MLflow Model
        shell: bash -l {0}
        run: |
          conda activate smsml_env
          mlflow models build-docker -m Workflow-CI/MLProject/mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/model -n fiqih-mlflow-model

      - name: Push Docker Image
        run: |
          docker tag fiqih-mlflow-model ${{ secrets.DOCKER_USERNAME }}/fiqih-mlflow-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fiqih-mlflow-model:latest
